apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ticket-service-monitor.yaml

images:
- name: admin-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-admin-service
  newTag: e639ed073f26559c7e989d777b5945bc307242c3
- name: ai-chatbot-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-ai-chatbot-service
  newTag: 5f6bd860000cae1c63bae2b2b3f7d3cc8700e11c
- name: auth-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-auth-service
  newTag: a7900ffe7c008222dae4ee0e8d47b819144d660a
- name: game-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-game-service
  newTag: 68225127819f57ae748271d4172f7311e6757e3c
- name: order-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-order-service
  newTag: a90240964fb1d5779ac1eb5ecf03649487c43b9e
- name: seat-lock-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-seat-lock-service
  newTag: f5f18495a21849994e340497f4927fc8fe671d00
- name: ticket-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-ticket-service
  newTag: 70a645ff1d7c8d72ec05642f81f88518e7c31655
- name: ticket-worker-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-ticket-worker-service
  newTag: 68225127819f57ae748271d4172f7311e6757e3c
- name: waiting-room-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-waiting-room-service
  newTag: 2cba90f06a11dde2001f217841b18cbcff23cd55
