apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ticket-service-monitor.yaml

images:
- name: admin-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-admin-service
  newTag: 5f3b2d0e007240bc02c8686f88fcbce23a97a003
- name: ai-chatbot-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-ai-chatbot-service
  newTag: 5f3b2d0e007240bc02c8686f88fcbce23a97a003
- name: auth-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-auth-service
  newTag: 7b49b63fd608ce41b58ae284cdf42b9e3961a04d
- name: game-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-game-service
  newTag: 5f3b2d0e007240bc02c8686f88fcbce23a97a003
- name: order-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-order-service
  newTag: 5f3b2d0e007240bc02c8686f88fcbce23a97a003
- name: seat-lock-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-seat-lock-service
  newTag: 5f3b2d0e007240bc02c8686f88fcbce23a97a003
- name: ticket-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-ticket-service
  newTag: cf0d84dea8f3c217c61f72d39112a722281adef2
- name: ticket-worker-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-ticket-worker-service
  newTag: 5f3b2d0e007240bc02c8686f88fcbce23a97a003
- name: waiting-room-service
  newName: 740831361032.dkr.ecr.ap-northeast-2.amazonaws.com/dev-waiting-room-service
  newTag: cb0c96e8eb291df20401487a5566a0aee6334a90
