apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: baselink-backend-monitor # 이름도 멋지게 변경!
  namespace: baselink-dev
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      argocd.argoproj.io/instance: baselink-app # 📍 baselink-app에 속한 "모든" 서비스를 긁어와!
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s