kube-prometheus-stack:
  defaultRules:
    create: true

  alertmanager:
    config:
      global:
        resolve_timeout: 5m
      route:
        receiver: "null"
        group_by: ["namespace"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        routes:
          - matchers:
              - alertname = "Watchdog"
            receiver: "null"
          - matchers:
              - source = "ai-analysis"
            receiver: "null"
      receivers:
        - name: "null"

  grafana:
    grafana.ini:
      server:
        domain: baselink.kro.kr
        root_url: "https://baselink.kro.kr/grafana/"
        serve_from_sub_path: true
      security:
        allow_embedding: true
      auth.anonymous:
        enabled: true
        org_role: Viewer
    adminPassword: "Password123!"
    additionalDataSources:
      - name: Jaeger
        type: jaeger
        url: http://jaeger.monitoring:16686
        access: proxy
        isDefault: false
