kube-prometheus-stack:
  defaultRules:
    create: true

  grafana:
    grafana.ini:
      server:
        domain: baselink.kro.kr
        root_url: "https://baselink.kro.kr/grafana/"
        serve_from_sub_path: true
    adminPassword: "Password123!"  # 원하는 비밀번호로 변경
