apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - workloads.yaml
  - waiting-room-rbac.yaml
  - services.yaml
  - ingress.yaml
  - keda.yaml
  - pdb.yaml
