apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ticket-service-pdb
  namespace: baselink-dev
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: ticket-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: seat-lock-service-pdb
  namespace: baselink-dev
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: seat-lock-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: waiting-room-service-pdb
  namespace: baselink-dev
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: waiting-room-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: baselink-dev
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: auth-service
