apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-runtime
  namespace: baselink-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::740831361032:role/baselink-dev-backend-runtime-irsa

